version: '3'

services:
  namenode:
    image : trquoctoann/hadoop_namenode
    build:
      context: ./hadoop
      dockerfile: Dockerfile
      args:
        FORMAT_NAMENODE_COMMAND: hdfs namenode -format
    container_name: namenode
    hostname: namenode
    networks:
      - hadoop_network
    volumes:
      - namenode_metadata:/home/hadoop/hdfs_name
    command: bash -c  "
        hadoop-daemon.sh --config /usr/local/hadoop/etc/hadoop start namenode
        && hadoop-daemon.sh --config /usr/local/hadoop/etc/hadoop start secondarynamenode
        && yarn-daemon.sh --config /usr/local/hadoop/etc/hadoop start resourcemanager
        && mr-jobhistory-daemon.sh start historyserver
        && tail -f /dev/null"
    ports:
      - 50070:50070
      - 8088:8088
      - 9000:9000
    restart: always

  datanode1:
    image : trquoctoann/hadoop
    container_name: datanode1
    hostname: datanode1
    networks:
      - hadoop_network
    volumes:
      - datanode1_data:/home/hadoop/hdfs_data
    depends_on:
      - namenode
    command: bash -c  " 
         hadoop-daemon.sh --config /usr/local/hadoop/etc/hadoop start datanode
         && yarn-daemon.sh --config /usr/local/hadoop/etc/hadoop start nodemanager
         && tail -f /dev/null"
    restart: always

  datanode2:
    image : trquoctoann/hadoop
    container_name: datanode2
    hostname: datanode2
    networks:
      - hadoop_network
    volumes:
      - datanode2_data:/home/hadoop/hdfs_data
    depends_on:
      - namenode
    command: bash -c  " 
         hadoop-daemon.sh --config /usr/local/hadoop/etc/hadoop start datanode
         && yarn-daemon.sh --config /usr/local/hadoop/etc/hadoop start nodemanager
         && tail -f /dev/null"
    restart: always

  hiveserver2:
    image: trquoctoann/hive
    container_name: hiveserver2
    hostname: hiveserver2
    networks:
      - hadoop_network
    depends_on:
      - namenode
      - datanode1
      - datanode2
    command: bash -c "
        /usr/local/hadoop/bin/hadoop fs -mkdir -p /tmp
        && /usr/local/hadoop/bin/hadoop fs -mkdir -p /warehouse
        && /usr/local/hadoop/bin/hadoop fs -chmod 777 /tmp
        && /usr/local/hadoop/bin/hadoop fs -chmod 777 /warehouse
        && /usr/local/hive/bin/hive --service hiveserver2
        && tail -f /dev/null"
    ports:
      - 10000:10000
      - 10002:10002
    restart: on-failure

  metastore-database:
    image: mysql
    container_name: metastore-database
    hostname: metastore-database
    networks:
      - hadoop_network
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - metastore_data:/var/lib/mysql
    depends_on:
      - hiveserver2
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always

  metastore-server:
    image: trquoctoann/hive
    container_name: metastore-server
    hostname: metastore-server
    networks:
      - hadoop_network
    command: bash -c "
      /usr/local/hive/bin/hive --service metastore
      && tail -f /dev/null"
    depends_on:
      - metastore-database
    restart: always

volumes:
  namenode_metadata:
  datanode1_data:
  datanode2_data:
  metastore_data:

networks:
  hadoop_network:
    driver: bridge